env: "local"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "myuser"
  password: "mypass"
pg_database:
  user: "admin"
  password: "admin"
  db_name: "urlshortenerdb"